'use client'

import { BookCheck, BookOpen, Heart, Library, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { BookCoverImage } from '@/components/ui/book-cover-image'
import type { Book } from '@/lib/book-data'
import type { ReadingRecord, ReadingStatus } from '@/lib/reading-storage'
import { ReadingControls, WishlistButton } from './reading-controls'

export function ReadingStats({ wishlistCount, history }: { wishlistCount: number; history: ReadingRecord[] }) {
  const stats = [
    { label: 'Wishlisted', value: wishlistCount, icon: Heart },
    { label: 'Reading now', value: history.filter((item) => item.status === 'Reading').length, icon: BookOpen },
    { label: 'Completed', value: history.filter((item) => item.status === 'Completed').length, icon: BookCheck },
    { label: 'Reading list', value: history.length, icon: Library },
  ]
  return <section aria-label="Reading statistics" className="mx-auto grid max-w-7xl gap-4 px-5 py-10 sm:grid-cols-2 lg:grid-cols-4 lg:px-8">{stats.map(({ label, value, icon: Icon }) => <article key={label} className="flex items-center gap-4 rounded-2xl border border-border bg-card p-5 shadow-sm"><span className="flex size-11 items-center justify-center rounded-xl bg-secondary text-accent-foreground"><Icon className="size-5" /></span><div><strong className="font-serif text-3xl">{value}</strong><p className="text-sm text-muted-foreground">{label}</p></div></article>)}</section>
}

export function WishlistSection({ books, onRemove, onSelect, onStart }: { books: Book[]; onRemove: (isbn: string) => void; onSelect: (book: Book) => void; onStart: (book: Book) => void }) {
  return <section id="wishlist" className="mx-auto flex max-w-7xl flex-col gap-8 px-5 py-20 lg:px-8"><div><p className="mb-3 text-xs font-bold tracking-[.2em] text-accent-foreground">SAVED FOR LATER</p><h2 className="font-serif text-4xl font-semibold">Your Wishlist</h2><p className="mt-3 text-muted-foreground">Books you want to keep close for your next reading season.</p></div>{books.length ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{books.map((book) => <article key={book.isbn} className="flex gap-4 rounded-2xl border border-border bg-card p-4 shadow-sm"><button onClick={() => onSelect(book)} aria-label={`View ${book.title}`}><BookCoverImage isbn={book.isbn} thumbnail={(book as any).thumbnail} title={book.title} author={book.author} genre={book.genre} alt={`Cover of ${book.title}`} className="aspect-[2/3] w-24 rounded-md object-cover" /></button><div className="flex min-w-0 flex-1 flex-col gap-3"><div><h3 className="text-pretty font-serif text-lg leading-tight">{book.title}</h3><p className="mt-1 text-sm text-muted-foreground">{book.author}</p></div><div className="mt-auto flex flex-wrap gap-2"><Button size="sm" onClick={() => onStart(book)}>Start Reading</Button><WishlistButton active compact onToggle={() => onRemove(book.isbn)} /></div></div></article>)}</div> : <div className="flex flex-col items-center gap-4 rounded-3xl border border-dashed border-border bg-card px-6 py-16 text-center"><Heart className="size-9 text-accent-foreground" /><h3 className="font-serif text-2xl">Your wishlist is ready for a first chapter.</h3><p className="max-w-lg text-muted-foreground">Tap the heart on any book to save it here.</p><Button onClick={() => document.getElementById('explore')?.scrollIntoView({ behavior: 'smooth' })}>Explore Books</Button></div>}</section>
}

export function ReadingHistorySection({ records, booksByIsbn, filter, onFilter, onProgress, onStatus, onRemove, onSelect }: { records: ReadingRecord[]; booksByIsbn: Map<string, Book>; filter: 'All' | ReadingStatus; onFilter: (filter: 'All' | ReadingStatus) => void; onProgress: (isbn: string, value: number) => void; onStatus: (isbn: string, status: ReadingStatus) => void; onRemove: (isbn: string) => void; onSelect: (book: Book) => void }) {
  const visible = records.filter((record) => filter === 'All' || record.status === filter)
  return <section id="history" className="bg-secondary/60 py-20"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-5 lg:px-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-3 text-xs font-bold tracking-[.2em] text-accent-foreground">YOUR READING LIFE</p><h2 className="font-serif text-4xl font-semibold">Reading History</h2><p className="mt-3 text-muted-foreground">Track every book from first page to finished story.</p></div><div className="flex flex-wrap gap-2">{(['All', 'Want to Read', 'Reading', 'Completed'] as const).map((item) => <Button key={item} size="sm" variant={filter === item ? 'default' : 'outline'} onClick={() => onFilter(item)}>{item}</Button>)}</div></div>{visible.length ? <div className="grid gap-5 lg:grid-cols-2">{visible.map((record) => { const book = booksByIsbn.get(record.isbn); if (!book) return null; return <article key={record.isbn} className="grid gap-5 rounded-2xl border border-border bg-card p-5 shadow-sm sm:grid-cols-[110px_1fr]"><button onClick={() => onSelect(book)} aria-label={`View ${book.title}`}><BookCoverImage isbn={book.isbn} thumbnail={(book as any).thumbnail} title={book.title} author={book.author} genre={book.genre} alt={`Cover of ${book.title}`} className="mx-auto aspect-[2/3] w-28 rounded-md object-cover" /></button><div className="flex min-w-0 flex-col gap-4"><div className="flex items-start justify-between gap-3"><div><span className="inline-flex rounded-full bg-secondary px-3 py-1 text-xs font-semibold text-accent-foreground">{record.status}</span><h3 className="mt-3 font-serif text-xl">{book.title}</h3><p className="text-sm text-muted-foreground">{book.author} · Updated {new Date(record.lastReadAt).toLocaleDateString()}</p></div><Button size="icon-sm" variant="ghost" onClick={() => onRemove(record.isbn)} aria-label={`Remove ${book.title} from history`}><X /></Button></div><ReadingControls record={record} onStart={() => undefined} onProgress={(value) => onProgress(record.isbn, value)} onStatus={(status) => onStatus(record.isbn, status)} /></div></article>})}</div> : <div className="flex flex-col items-center gap-4 rounded-3xl border border-dashed border-border bg-card px-6 py-16 text-center"><BookOpen className="size-9 text-accent-foreground" /><h3 className="font-serif text-2xl">No books in this view yet.</h3><p className="text-muted-foreground">Start reading a book or choose a different filter.</p></div>}</div></section>
}

